name: ploopyver2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  crypto: ^3.0.3
  
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  provider: ^6.1.5+1
  local_auth: ^2.3.0
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_markdown_plus:
  flutter_dotenv: ^5.1.0  

  flutter_compass: ^0.8.1
  permission_handler: ^11.3.1

  flutter_local_notifications: ^17.2.3
  wakelock_plus: ^1.2.8  
  audioplayers: ^6.1.0 

  shared_preferences: ^2.3.2
  uuid: ^4.5.1 

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1

  cunning_document_scanner: ^1.2.3     # ML Kit Document Scanner (Google official!)
  pdf: ^3.11.1                          # Generate PDF
  printing: ^5.13.4                     # Preview & share PDF
  path_provider: ^2.1.5                # File storage
  image_gallery_saver_plus: ^4.0.1     # Save to gallery
  share_plus: ^10.1.2  

  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Map (OpenStreetMap)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Image Caching
  cached_network_image: ^3.3.1


  go_router: ^13.2.0

  # UI
  shimmer: ^3.0.0

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get_it: ^9.2.1
  connectivity_plus: ^7.1.1
  supabase_flutter: ^2.12.4
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/badge/
