create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  subject text,
  deadline timestamptz not null,
  details text,
  color bigint not null default 4294923776,
  icon_name text default 'task',
  is_pinned boolean not null default false,
  is_completed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists tasks_user_deadline_idx
  on public.tasks (user_id, deadline);

create index if not exists tasks_user_pinned_idx
  on public.tasks (user_id, is_pinned);

alter table public.tasks enable row level security;

drop policy if exists "Users can read their own tasks" on public.tasks;
create policy "Users can read their own tasks"
  on public.tasks for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own tasks" on public.tasks;
create policy "Users can insert their own tasks"
  on public.tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own tasks" on public.tasks;
create policy "Users can update their own tasks"
  on public.tasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own tasks" on public.tasks;
create policy "Users can delete their own tasks"
  on public.tasks for delete
  using (auth.uid() = user_id);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  location text,
  description text,
  link text,
  color bigint not null default 4294923776,
  icon_name text default 'event',
  repeat_type text not null default 'None',
  repeat_until timestamptz,
  created_at timestamptz not null default now(),
  constraint schedules_end_after_start check (end_time > start_time)
);

create index if not exists schedules_user_start_idx
  on public.schedules (user_id, start_time);

alter table public.schedules enable row level security;

drop policy if exists "Users can read their own schedules" on public.schedules;
create policy "Users can read their own schedules"
  on public.schedules for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own schedules" on public.schedules;
create policy "Users can insert their own schedules"
  on public.schedules for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own schedules" on public.schedules;
create policy "Users can update their own schedules"
  on public.schedules for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own schedules" on public.schedules;
create policy "Users can delete their own schedules"
  on public.schedules for delete
  using (auth.uid() = user_id);
