import 'package:flutter/material.dart';

class ChatDummyData {
  static final List<Map<String, dynamic>> chats = [
    {
      'name': 'Andi Saputra',
      'avatar': 'A',
      'color': Color(0xFF4D96FF),
      'lastMessage': 'Wah mantap! Streak 30 hari keren banget 🔥',
      'time': '2m',
      'unread': 2,
      'isOnline': true,
      'isTyping': false,
    },
    {
      'name': 'Bella Pratiwi',
      'avatar': 'B',
      'color': Color(0xFFFF6B6B),
      'lastMessage': 'Nanti bareng belajar di perpus yuk',
      'time': '15m',
      'unread': 0,
      'isOnline': true,
      'isTyping': true,
    },
    {
      'name': 'Study Group Flutter 🚀',
      'avatar': '🚀',
      'color': Color(0xFF6BCB77),
      'lastMessage': 'Doni: Besok kita meeting jam berapa?',
      'time': '1h',
      'unread': 5,
      'isOnline': false,
      'isTyping': false,
      'isGroup': true,
    },
    {
      'name': 'Cindy Wijaya',
      'avatar': 'C',
      'color': Color(0xFFFFD166),
      'lastMessage': 'Makasih ya buat materinya! 💖',
      'time': '3h',
      'unread': 0,
      'isOnline': false,
      'isTyping': false,
    },
    {
      'name': 'Doni Herlambang',
      'avatar': 'D',
      'color': Color(0xFFB79CED),
      'lastMessage': 'Kamu udah review PR-nya?',
      'time': '5h',
      'unread': 1,
      'isOnline': true,
      'isTyping': false,
    },
    {
      'name': 'Erin Putri',
      'avatar': 'E',
      'color': Color(0xFFFF8C42),
      'lastMessage': 'Keep going! Aku percaya sama kamu 💪',
      'time': '1d',
      'unread': 0,
      'isOnline': false,
      'isTyping': false,
    },
    {
      'name': 'Ploopy Community 🌱',
      'avatar': '🌱',
      'color': Color(0xFF4D96FF),
      'lastMessage': 'Fajar: Selamat datang semuanya!',
      'time': '2d',
      'unread': 12,
      'isOnline': false,
      'isTyping': false,
      'isGroup': true,
    },
  ];
}