import 'package:flutter/material.dart';

class EventDummyData {
  static final List<Map<String, dynamic>> events = [
    {
      'title': 'Flutter Study Group',
      'category': 'Belajar',
      'date': '15 Okt 2024',
      'time': '19:00 - 21:00',
      'location': 'Online via Zoom',
      'distance': null,
      'participants': 45,
      'maxParticipants': 100,
      'coverColor': Color(0xFF4D96FF),
      'emoji': '💻',
      'joined': true,
    },
    {
      'title': 'Morning Run Together',
      'category': 'Olahraga',
      'date': '16 Okt 2024',
      'time': '06:00 - 07:30',
      'location': 'Taman Menteng',
      'distance': '4.5 km',
      'participants': 23,
      'maxParticipants': 50,
      'coverColor': Color(0xFF6BCB77),
      'emoji': '🏃',
      'joined': false,
    },
    {
      'title': 'UI/UX Workshop',
      'category': 'Workshop',
      'date': '18 Okt 2024',
      'time': '13:00 - 16:00',
      'location': 'Creative Hub Jakarta',
      'distance': '2.8 km',
      'participants': 67,
      'maxParticipants': 80,
      'coverColor': Color(0xFFFF8C42),
      'emoji': '🎨',
      'joined': false,
    },
    {
      'title': 'Meditation & Mindfulness',
      'category': 'Wellness',
      'date': '20 Okt 2024',
      'time': '07:00 - 08:00',
      'location': 'Taman Suropati',
      'distance': '3.1 km',
      'participants': 18,
      'maxParticipants': 30,
      'coverColor': Color(0xFFB79CED),
      'emoji': '🧘',
      'joined': true,
    },
    {
      'title': 'Book Club Discussion',
      'category': 'Komunitas',
      'date': '22 Okt 2024',
      'time': '15:00 - 17:00',
      'location': 'Perpustakaan Nasional',
      'distance': '1.2 km',
      'participants': 12,
      'maxParticipants': 20,
      'coverColor': Color(0xFFFFD166),
      'emoji': '📚',
      'joined': false,
    },
  ];
}