// File: /schedule_dummy_data.dart

import 'package:flutter/material.dart';

class ScheduleDummyData {
  static List<Map<String, dynamic>> get todayItems => [
        {
          'title': 'Meditasi & Relaksasi',
          'time': '06.30',
          'icon': Icons.self_improvement_rounded,
          'color': Color(0xFF18181B),
          'done': true,
          'duration': '15 mnt',
          'durationNum': 15,
          // ── Fields baru ──
          'location': ' ',
          'description': 'Sesi meditasi pagi untuk memulai hari dengan tenang dan fokus',
          'startDate': DateTime.now(),
          'startTime': const TimeOfDay(hour: 6, minute: 30),
          'endDate': DateTime.now(),
          'endTime': const TimeOfDay(hour: 6, minute: 45),
          'repeat': 'Harian',
        },
        {
          'title': 'Belajar Matematika',
          'time': '09.00',
          'icon': Icons.calculate_rounded,
          'color': Color(0xFF3F3F46),
          'done': false,
          'duration': '60 mnt',
          'durationNum': 60,
          'location': 'Ruang 301 Gedung A',
          'description': 'Mempelajari Bab 5: Kalkulus Diferensial',
          'startDate': DateTime.now(),
          'startTime': const TimeOfDay(hour: 9, minute: 0),
          'endDate': DateTime.now(),
          'endTime': const TimeOfDay(hour: 10, minute: 0),
          'repeat': 'Tidak Berulang',
        },
        {
          'title': 'Baca Buku',
          'time': '13.00',
          'icon': Icons.menu_book_rounded,
          'color': Color(0xFF52525B),
          'done': false,
          'duration': '30 mnt',
          'durationNum': 30,
          'location': 'Perpustakaan',
          'description': 'Membaca buku fiksi untuk meningkatkan vocabulary',
          'startDate': DateTime.now(),
          'startTime': const TimeOfDay(hour: 13, minute: 0),
          'endDate': DateTime.now(),
          'endTime': const TimeOfDay(hour: 13, minute: 30),
          'repeat': 'Mingguan',
        },
        {
          'title': 'Olahraga Ringan',
          'time': '16.00',
          'icon': Icons.fitness_center_rounded,
          'color': Color(0xFF71717A),
          'done': false,
          'duration': '45 mnt',
          'durationNum': 45,
          'location': 'Halaman Rumah',
          'description': 'Latihan kardio ringan dan stretching',
          'startDate': DateTime.now(),
          'startTime': const TimeOfDay(hour: 16, minute: 0),
          'endDate': DateTime.now(),
          'endTime': const TimeOfDay(hour: 16, minute: 45),
          'repeat': 'Tidak Berulang',
        },
      ];

  static List<Map<String, dynamic>> get todayTasks => [
        {
          'title': 'Tugas Matematika Bab 5',
          'subject': 'Matematika',
          'icon': Icons.assignment_rounded,
          'color': Color(0xFF18181B),
          'done': false,
          'due': 'Hari ini',
        },
        {
          'title': 'Baca Chapter 3-4',
          'subject': 'Bahasa Inggris',
          'icon': Icons.book_rounded,
          'color': Color(0xFF3F3F46),
          'done': false,
          'due': 'Besok',
        },
        {
          'title': 'Makalah IPS',
          'subject': 'IPS',
          'icon': Icons.article_rounded,
          'color': Color(0xFF52525B),
          'done': false,
          'due': 'Kemarin',
        },
      ];
}